version: '3.8'

services:
  db:
    container_name: postgres_database_container
    restart: always
    image: postgres:17.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=platform_dev_db
    volumes:
      - ../../database:/var/lib/postgresql

  pgadmin:
    container_name: postgres_pg_admin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8888:80"